In [8]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import seaborn

In [9]:
iris = seaborn.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
X = iris.drop('species', axis = 1)
y = iris['species']

In [11]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size = 0.25, random_state = 42)

In [13]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print('sample predictions', y_pred[::-5])

sample predictions [0 1 2 0 1 0 2 2]


In [14]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [15]:
def class_metrics(cm, index):
    tp = cm[index, index]
    fp = cm[:, index].sum() - tp
    fn = cm[index, :].sum() - tp
    tn = cm.sum() - tp - fp - fn
    return tp, fp, fn, tn
    

In [16]:
classes = np.unique(y_test)

In [17]:
print('Matrix per class')
for i, class_name in enumerate(classes):
    tp, fp, fn, tn = class_metrics(cm, i)
    accuracy = (tp+tn)/(tp+tn+fn+fp)
    precision = tp / (tp+fp) if (tp+fp)>0 else 0
    recall = tp / (tp+fn) if (tp+fn)>0 else 0

    print(f'Class {class_name}')
    print(f'TP: {tp}, FP: {fp}, FN: {fn}, TN: {tn}')
    print(f'Accuracy: {accuracy:.2f}')
    print(f'Precision: {precision:.2f}')
    print(f'Recall: {recall:.2f}')

Matrix per class
Class 0
TP: 15, FP: 0, FN: 0, TN: 23
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
Class 1
TP: 11, FP: 0, FN: 0, TN: 27
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
Class 2
TP: 12, FP: 0, FN: 0, TN: 26
Accuracy: 1.00
Precision: 1.00
Recall: 1.00


In [18]:
overall_accuracy = accuracy_score(y_test, y_pred)
print(f'Overall accuracy: {overall_accuracy}')

Overall accuracy: 1.0


In [19]:
print('Classification Report: \n', classification_report(y_test, y_pred))

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

