In [29]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import seaborn

In [18]:
iris = seaborn.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
X = iris.drop('species', axis = 1)
y = iris['species']

In [20]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size = 0.25, random_state = 42)

In [23]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print('sample predictions', y_pred[::-5])

sample predictions [0 1 2 0 1 0 2 2]


In [28]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [30]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        15\n           1       1.00      1.00      1.00        11\n           2       1.00      1.00      1.00        12\n\n    accuracy                           1.00        38\n   macro avg       1.00      1.00      1.00        38\nweighted avg       1.00      1.00      1.00        38\n'

In [ ]:
def class_metrics(cm, class_index):
    